//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DressEntities : DbContext
    {
        public DressEntities()
            : base("name=DressEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<DressCategory> DressCategories { get; set; }
        public virtual DbSet<DressDefinition> DressDefinitions { get; set; }
        public virtual DbSet<DressImage> DressImages { get; set; }
        public virtual DbSet<Image> Images { get; set; }
    }
}
